### ISSUE TITLE
Empty array is changing to empty object on rehydrate

### ISSUE THREAD

**Issue by asciiman** [rt2zz/redux-persist#215]
```
const initialState = [];

export default function(state = initialState, action) {
  switch (action.type) {
  case constants.UPDATE_QUESTIONS:
    return action.questions;
  }
  return state;
}
```

To test I deleted the app and reinstalled and started the app.  The questions state started as [] and did not change.  I restarted the app and then:

Before rehydrate:
![image](https://cloud.githubusercontent.com/assets/645336/20464026/e8af57ca-af3f-11e6-82ad-a0f7ac86918d.png)

After rehydrate:
![image](https://cloud.githubusercontent.com/assets/645336/20464030/f81fb042-af3f-11e6-8550-6c8a529a7f7b.png)

redux-persist: 3.5.0

**Comment by asciiman** [comment]
It only seems to be an issue if the empty array is the root state of the reducer.

If the initial state is:
```
const initialState = { data: []};
```

Then it rehydrates correctly as an array.

**Comment by marvinhagemeister** [comment]
That is quite curious. I can't reproduce it locally with a simple test case. Can you check if the problem exists when writing or restoring the store in your app? Most likely you are using the LocalStorage backend and the contents can be easily inspected in the chrome or firefox devtools.

**Comment by asciiman** [comment]
I'm using AsyncStorage with RN.  How can I debug it there?

**Comment by rt2zz** [comment]
@asciiman redux persist assumes state is a plain object (or really any type of Map as long as the correct config is provided). This assumption is useful for making persistence performant (store one keyspace at a time) and for making rehydration convenient (shallow-merge autorehydrate). 

While we do not have a test case for this scenario, an inspection of getStoredState leads me to believe your observation is correct, it would indeed return an object for your case (https://github.com/rt2zz/redux-persist/blob/master/src/getStoredState.js#L33).

Any ideas on how we can improve this? One option would be to detect that the state is non-map and  act accordingly. This is such an edge case however I wonder if you might be better served with https://github.com/michaelcontento/redux-storage which while a heavier api, should handle your use case out of the box.

**Comment by rt2zz** [comment]
can you try again on v5.3+, we now detect if the substate is an array and if so skip shallow merging state. i.e. this issue should be resolved.

**Comment by jtang-ml** [comment]
Having same issue on v5.10 but in my case, the state for the persisted reducer itself is an array. Is it somehow related?

**Comment by mcmonkeys1** [comment]
2020, this is still occurring when root is a solo array.
I have a nested persist root it overwrites my initialState = [] with an object containing {_persist.. rehydrated... }

**Comment by Majiedo** [comment]
I have the same problem any idea how to solve it ?

**Comment by romulororiz** [comment]
I had to change my structure do initialState = { data: [...] } and then it worked how it's supposed to

**Comment by romulororiz** [comment]
I had to change my structure to:

initialState = { data: [ ... ] }

now it works the way it's supposed to

**Comment by mattlohkamp** [comment]
This is still an unaddressed bug - root state arrays are converted to objects, as can be seen in console logs here - 

https://stackblitz.com/edit/vitejs-vite-xxymwzsr?file=src%2FnumberCollectionSlice.ts

```js
const numberCollectionSlice = createSlice({
  name: 'numberCollection',
  initialState: [1, 3, 5, 7],
  reducers: {},
});
```

state.numberCollection should be an array, but once persisted, it's an object, with additional properties added.

```
App.tsx:9 App numberCollection: {0: 11: 32: 53: 7_persist: {version: -1, rehydrated: true}}[[Prototype]]: Object
```

I've tried to get around this using transforms, but when I console.log out the inbound/outbound state, I see that it's operating on _each item in the array_, rather than on _the array itself_.

```
configureStore.ts:17 state persist transform outbound: 1
configureStore.ts:17 state persist transform outbound: 3
configureStore.ts:17 state persist transform outbound: 5
configureStore.ts:17 state persist transform outbound: 7
configureStore.ts:17 state persist transform outbound: {version: -1, rehydrated: true}
```

There's no reason root state couldn't be an array, and it's odd that redux-persist appears to be unable to handle this.
