### ISSUE TITLE
Data sporadically erased (React Native)

### ISSUE THREAD

**Issue by jesperlndk** [rt2zz/redux-persist#809]
## Introduction

We are building a React Native app, and we are using [redux-persist](https://github.com/rt2zz/redux-persist) together with [redux-persist-filesystem-storage](https://github.com/robwalkerco/redux-persist-filesystem-storage) to store data on the phone.

## The issue

We are experiencing that sometimes after an app update (via TestFlight and Play Store) all the app data just is erased. The app is simply back to initial state. This can happen for both iOS and Android.

## Steps to reproduce

Well, this is where it get's annoying.. We haven't yet been able to get the exact steps to reproduce the issue. It just happens sporadically. We have around 100 beta testers, and ~20 people have reported this issue. Both on iOS and Android, and there was no link between a specific app update version or anything.

## Similar issues

We have of course looked around on GitHub, trying to find similar issues. At first we thought https://github.com/rt2zz/redux-persist/issues/199 was our issue, so that's why we switched to [redux-persist-filesystem-storage](https://github.com/robwalkerco/redux-persist-filesystem-storage) from AsyncStorage. But that didn't help. And it looks like other people are still experiencing it as well: https://github.com/robwalkerco/redux-persist-filesystem-storage/issues/2

## Additional information

* Platform: React Native, iOS and Android
* `redux-persist` version: 4.9.1
* `redux-persist-filesystem-storage` version: 1.10
* Additional components: [redux-persist-migrate](https://github.com/wildlifela/redux-persist-migrate) version 4.1.0 + [redux-persist-transform-filter](https://github.com/edy/redux-persist-transform-filter) version 0.0.9

## Final note

Although this issue is somewhat vaguely described, I'm submitting it to raise awareness, because we think it's a rather important issue if it really _IS_ an existing bug. Maybe someone out there is looking for help with the same issue - so here it is.

_I have created the same issue on redux-persist-filesystem-storage:_ https://github.com/robwalkerco/redux-persist-filesystem-storage/issues/14

**Comment by felixus95** [comment]
+1 !

**Comment by alexmngn** [comment]
We're actually having the exact same problem in my company. We are just using AsyncStorage though.

**Comment by jrmurad** [comment]
Same here. I started looking into it and I think what's happening is the `getItem()` Promise on app load rejects with an error. That error is passed to the `REHYDRATE` action. The action does not consider the error and just writes `undefined` to the store, causing the `setItem` middleware to run and "erasing" the data.

I am currently looking for issues with a suggested fix or a PR. Might make my own PR but I'm not sure what correct behavior should be. Probably just to not write anything to local store if `getItem` failed. And I might need to add a new error handler to the config so consumer can handle when a rehydration error occurs.

**Comment by alanlanglois** [comment]
@jrmurad I moved from AsyncStorage to FSStorage (based on react-native-fs) and the issue seem to appear way less often, but it still occurs from time to time on some Android devices.
An appropriate fix would be to have a way to detect and display they error and stop the rehydrate process.

**Comment by lilosir** [comment]
Same issue, any updates?

**Comment by lukebrandonfarrell** [comment]
I can confirm that this still happens when using FSStorage. It happens of both v5 & v4. Seems to have something to do with the `autoRehydrate` which is not getting logged and data not persisted in some cases.

**Comment by lukebrandonfarrell** [comment]
After more testing it seems to be working with [redux-persist-filesystem-storage](https://github.com/robwalkerco/redux-persist-filesystem-storage) without erasing data randomly. It could be something to do with AsyncStorage.

**Comment by alanlanglois** [comment]
Anyone found a solution @jrmurad @jesperlndk @alexmngn?

**Comment by lukebrandonfarrell** [comment]
@alanlanglois Using [redux-persist-filesystem-storage](https://github.com/robwalkerco/redux-persist-filesystem-storage) worked for me. Using in production.

**Comment by alanlanglois** [comment]
@lukebrandonfarrell 
Few mounths ago I gave it a try, unfortunatly it wasn't working with an expo detached project.  (rn-fetch-blob wasn't at least). 
I then changed a little the lib to use react-native-fs instead of rn-fetch-blob. 
It fixed the problem in most cases, but I still have the issue from time to time (way less often). 
Do you have a large audience are you sure it totally fixed your problem? (I got like 10K+ install on Android)

**Comment by ssorallen** [comment]
I was able to reproduce the issue by setting `timeout` to something incredibly low like 10ms. The store was consistently overwritten by `initialState`. That's when I tested a few weeks ago, and I didn't write a test. I'd like to write a test to reproduce it, but I wanted to mention that in case anyone else is able to investigate further.

`timeout` is a key in the persist config, but it is not yet documented in the README.

**Comment by alanlanglois** [comment]
@ssorallen  I guess this is talked here: https://github.com/rt2zz/redux-persist/issues/717

**Comment by ssorallen** [comment]
redux-persist's `timeout` functionality definitely wipes out the store and rehydrates it with initial state. I don't know if that's the *only* issue here, but I have confirmed locally and in my own app that it does wipe out my store.

You can disable the timeout functionality entirely by passing `timeout: 0` in your persistConfig. If your store takes a while to rehydrate then the `PersistGate` will continue to show the `loading` state. If your store never rehydrates then the PersistGate will never go away. However, it won't ever hit the `timeout` functionality and wipe your store. Your users can refresh the app or whatever it takes in case that slow rehydration was transient.

A workaround I've discovered for my own use: kill redux-persist's `timeout` functionality. If the timeout hits, your store is rehydrated with the initial state and then persisted again to kill the state that is likely still loading.

In your persist config, prevent the [timeout setup (persistReducer.js#L88-99)](https://github.com/rt2zz/redux-persist/blob/v5.10.0/src/persistReducer.js#L88-L99):

```
const persistConfig: {
   ...
   timeout: 0, // The code base checks for falsy, so 0 disables
};
```

A complete solution for redux-persist would be to add a `timeout` component to `PersistGate` that would render if your timeout is it and stop the rehydration work. What it shouldn't do is then rehydrate your store with initialState, which is the current functionality.

**Comment by wmonecke** [comment]
Happening on my app as well! Some of my users have reported to me that all their journal data disappeared. 

````
"react": "16.8.3",
"react-native": "0.59.8",
"react-redux": "^6.0.0", 
"redux": "^4.0.1",
"redux-persist": "^5.10.0",
"redux-thunk": "^2.3.0",
````

**Comment by alxmrtnz** [comment]
I've been working on an **Expo-based** React Native app that encountered the same problem.

After trying the timeout fix mentioned above and finding that didn't work for us, **we ended up using [`redux-persist-expo-fs-storage`](https://github.com/nohac/redux-persist-expo-fs-storage) and haven't been experiencing the same problems since**.

If you're using **Expo**, I'd recommend trying that out as your storage solution. Just for reference, here's some more package.json info:

```
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-redux": "^5.1.0",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-persist-expo-fs-storage": "^1.2.2",
    "redux-thunk": "^2.3.0",
```

**Comment by webytecno** [comment]
This bug is also happening in our production app. We have a lot of users complaining because their data (stored using the library: **redux-persist-fs-storage**), is being sporadically erased... We tried adjusting the timeout config, but that didn't solve the problem. We are not using Expo. If anyone solved this issue, please help me with the solution. Many thanks!!!!

**Comment by svenlombaert** [comment]
We're experiencing the same issue as well now. I can give this information (which is about the same as the OP)

- It only happens on app update
- From our support tickets, seems to primarily happen on Android (we're pretty sure it's android only - but not 100% sure)
- We though we were hitting the timeout limit, which we disabled. We also added extra performance logging of the `persistStore` function when rehydrating. The longest execution time we had was 887ms (in production), so it's not hitting the timeout at all. Pretty sure that can be ruled out.
- Also switched from AsyncStorage to redux-persist-filesystem-storage , doesn't seem to make a difference.

If there's any way we can help out (by providing logs, setups, etc) please contact me. It's becoming a big problem for us and our users.

**Comment by ssorallen** [comment]
Is this repo maintained any more? These issues date back a full two years now, and the last commit to master was September 2019.

If this is affecting your production application and causing data loss, it might be time to find a replacement for redux-persist.

**Comment by svenlombaert** [comment]
Well, I think why people are still posting all the issues here is because when you're using redux, there doesn't seem to be a lot of alternative to redux-persist.

**Comment by Orange9000** [comment]
In my case explicitly setting the whitelisted reducers, as well as timeout to 0 in redux persist config actually helped. No more store data loss after an app restart after that.

**Comment by svenlombaert** [comment]
I think by now, I've tried every possible combination of workarounds. They always get persisted and rehydrated **except** on app update. We implemented our own solution now to persist a specific reducer which contained data that never gets synced with the server.

**Comment by lukebrandonfarrell** [comment]
Btw this issue drove us to build our own persist library (a year ago): https://github.com/aspect-apps/redux-persist-machine

As we got frustrated with little issues like this, we wanted a much simpler implementation, with more customisation over the data we load, and how we load it.

**Comment by wmonecke** [comment]
Does anyone have an update on this? This is actually making us lose customers.

**Comment by ArchanaNair** [comment]
Any fix on this issue?

**Comment by ssorallen** [comment]
@wmonecke @ArchanaNair If redux-persist is making you lose customers, I’d likely abandon this library. It has not been maintained in several years at this point. (see dates on issues and comments)

You might have more success with major version 5, but if these are decisions that impact your revenue then this library does not seem reliable enough.

**Comment by StuartGough7** [comment]
I managed to identify and solve the same issue on Android using redux persist with async storage. Here is what the problem was in my case:
As @jrmurad mentioned the error manifests itself on getItem. To identify it I patched the persistReducer.js as follows and threw an error instead of rehydrating with undefined:

`
diff --git a/node_modules/redux-persist/lib/persistReducer.js b/node_modules/redux-persist/lib/persistReducer.js
index 1116881..6aed0e7 100644
--- a/node_modules/redux-persist/lib/persistReducer.js
+++ b/node_modules/redux-persist/lib/persistReducer.js
@@ -94,6 +94,7 @@ function persistReducer(config, baseReducer) {
       if (typeof action.rehydrate !== 'function' || typeof action.register !== 'function') throw new Error('redux-persist: either rehydrate or register is not a function on the PERSIST action. This can happen if the action is being replayed. This is an unexplored use case, please open an issue and we will figure out a resolution.');
       action.register(config.key);
       getStoredState(config).then(function (restoredState) {
+        console.log('redux persist reducer')
         var migrate = config.migrate || function (s, v) {
           return Promise.resolve(s);
         };
@@ -102,11 +103,14 @@ function persistReducer(config, baseReducer) {
           _rehydrate(migratedState);
         }, function (migrateErr) {
           if (process.env.NODE_ENV !== 'production' && migrateErr) console.error('redux-persist: migration error', migrateErr);
-
-          _rehydrate(undefined, migrateErr);
+          console.log('redux persist migration error', migrateErr)
+          throw migrateErr
+          // _rehydrate(undefined, migrateErr);
         });
       }, function (err) {
-        _rehydrate(undefined, err);
+        console.log('redux persist error', err)
+        throw err
+        // _rehydrate(undefined, err);
       });
       return _objectSpread({}, baseReducer(restState, action), {
         _persist: {

`

In my case this yielded an error sometime later (due to this error being not very repeatable) as follows:

`
redux persist error [Error: Row too big to fit into CursorWindow requiredPos=0, totalRows=1]
`
This lead me to the local SQLite issue of trying to read big text entries for single rows exceeding the default of 4mb for a single row, and that indeed was the issue. A few thousand rows of text were being stored in the redux store under a single row.

Saving this as a JSON file and storing a reference to that file in redux solved the issue. You could expand that limit but I figured it's probably there for good reason. I hope this saves someone else.

**Comment by wmonecke** [comment]
@ssorallen I have been searching for a replacement with no success!

**Comment by Shazil1** [comment]
I am getting this issue where i store the userType in the redux-persist but when ever the app is updated it loses all its data and the app becomes un useable the user have to log out in order to store the userType from the api

**Comment by r1jsheth** [comment]
We are still facing this, seems like this repo is not actively maintained

**Comment by raj-flyfin** [comment]
> I think by now, I've tried every possible combination of workarounds. They always get persisted and rehydrated **except** on app update. We implemented our own solution now to persist a specific reducer which contained data that never gets synced with the server.

Would you mind sharing what did you do?

**Comment by r1jsheth** [comment]
> I think by now, I've tried every possible combination of workarounds. They always get persisted and rehydrated **except** on app update. We implemented our own solution now to persist a specific reducer which contained data that never gets synced with the server.

Would you mind sharing what did you do?

**Comment by haozhutw** [comment]
> For anyone experiencing data loss after app update on iOS, this is probably not the redux-persist issue, but of a storage engine, or its filesystem interaction logic, to be exact.
> 
> That my happen if a storage engine keeps persisted state in a document directory, path to which may look something like this `data/Containers/Data/Application/APP_UUID/Documents/`, where `APP_UUID` is a unique identifier which changes on app updates. I suggest, after an app update, storage engine, for some reason, tries to look for persisted state in an old directory, finds nothing, which in return causes `redux-persist` to revert the store to its default state.
> 
> Why does that happen is a mystery, since this error is not 100% reproducible.
> 
> In the end, that is just my suggestion, which may not be the case.

You are right, the `APP_UUID` may be changed after app update, but shouldn't the store engine save and query data from a relative path? `APP_UUID` may be changed, but the `Document` folder is always there. This should not be the case since same issue also happens on Android. This issue happens on production apps and it's still not resolved after 3 years. Looks like this library is not maintained, we need to try a replacement even though it's tough.

**Comment by jaydeep911** [comment]
In My case this same issue happen after updating expo version. 

Solution: 
// import FSStorage from "redux-persist-expo-fs-storage";
import FSStorage from "redux-persist-fs-storage";
/* 
Import change 
*/
const primary = {
  key: "root",
  timeout: 0,
  version: 1,
  keyPrefix: "",
  storage: FSStorage(),
  stateReconciler: autoMergeLevel2, // see "Merge Process" section for details.
};

ADD keyPrefix: "", in config. 
Hope this solutions work for others.

**Comment by Ti-tanium** [comment]
We are facing the same issue, and I think I find a way to reliably replicate this bug. On Android 9 emulator, almost every time I restart the app, the data is erased.

**Comment by wanted-o** [comment]
Hello, we had the same problem on production, data randomly erased on IOS. How we can resolve the issue? Someone has solution?

**Comment by kangfenmao** [comment]
fixed by https://github.com/rt2zz/redux-persist/issues/199#issuecomment-1473247158

**Comment by BhagavadGitaApp** [comment]
Even I had been tearing my hair off due to this issue but after much debugging, I found that it may not even be an issue with this library.

In my case it wasn't fixed by https://github.com/rt2zz/redux-persist/issues/199#issuecomment-1473247158.

So, I tried removing the redux-persist library itself and replaced it with my custom hook. (I have a use-case in my [app](https://play.google.com/store/apps/details?id=com.bhagavadgita.in.hindi.english&pli=1) to enable the user to save verses to their phone, so that they can revisit them later.)

```
// usePersistData.hooks.ts, called in the root app
const savedShloks = useSelector((state: RootState) => state.savedShloks);

  const dispatch = useDispatch();

  const reHydrateData = useCallback(async () => {
    try {
     // import {AsyncStore} from '../utils/storage.utils';
     // AsyncStore points to a wrapper on AsynStorage library for adding save and read events.

      const savedData = (await AsyncStore.getItem(PERSIST_DATA_KEY)) || '{}'; 
      const data = JSON.parse(savedData) as RootState;
       dispatch(actions.rehydrateSavedShlok(data.savedShloks));
    } catch (error) {
      // log
    }
  }, [dispatch]);

  useEffect(() => {
    // load from storage on mount
    reHydrateData();
  }, [reHydrateData]);

  const saveDataToDisk = useCallback(async (key: string, data: any) => { // 'any' since, any data can be saved here, as long as it can be stringified
    try {
      const savedData = (await AsyncStore.getItem(PERSIST_DATA_KEY)) || '{}';
      await AsyncStore.setItem(
        PERSIST_DATA_KEY,
        JSON.stringify({
          ...JSON.parse(savedData),
          [key]: data,
        }),
      );
    } catch (error) {
      // log
    }
  }, []);

  useEffect(() => {
    saveDataToDisk('savedShloks', savedShloks);
  }, [savedShloks, saveDataToDisk]);
```
  
However, **even after removing this library**, data was still getting sporadically erased. So, I changed the implementation of the `AsyncStore` util I had created, to use my own custom nativemodule for saving the data, instead of community AsyncStorage library, and lo! the issue was gone!.

Initially, this Nativemodule saved to SharedPreferences on Android, but it was later changed to use sqlLite instead. I don't know if I can plugin my custom Nativemodule into redux persist to test it out, but my guess is, it should work. Currently, its working seamlessly in production.

Hope this helps someone 😇

**Comment by jeroenheijmans** [comment]
I'm also in the progress of debugging a possible variant of this issue. I wanted to share what I have so far, and might edit to update this comment in the near future if I find out more. The solution you may want to implement depends on your application needs I suppose. I don't have a good solution yet for my own actual current production scenario, partially because I'm unsure yet which variant I'm (mostly) experiencing.

## Variant 1: misbehaving `transforms` (confirmed in production for me)

If I introduce an exception in the `transforms` that are applied after _reading_ from storage, things will blow up and store data might get reset to initial state. In pseudo-code (I don't have a clear repro at hand yet, have to extract that from our prod app):

```
const persistConfig = {
  key: 'root',
  storage: YourStorageHere,
  transforms: createTransform(
    (inboundState, key) => ({ ...inboundState, myRandomValue: Math.trunc(Math.random() * 10) }),
    (outboundState, key) => {
        if (myRandomValue[0] === 5) throw "simulated random error";
        return { ...outboundState };
    },
   { }
};
```

So every 1 in 10 times storage will have `myRandomValue === 5` and when it is _read_ from storage the tranform will crash. This simulates for example a more realistic NullReferenceException in the `outbound` function. And it will cause the state to be reset to initial state for your store.

## Variant 2a: storage timeouts (confirmed in snack.expo.dev)

Earlier comments, most notably [the one by @ssorallen](https://github.com/rt2zz/redux-persist/issues/809#issuecomment-437589932) already mention it might have to do with `timeout`s. I can in fact confirm that this is the case! I wrote this `storage` implementation and used it on snack.expo.dev to see the behavior in action. First, the code:

```javascript
const getDelay = () => Math.trunc(Math.random() * 10000);

function log(...args) {
  console.log(`[${new Date().toISOString().substring(11)}]`, ...args);
}

const persistConfig = {
  key: 'root',
  storage: {
    getItem(key) {
      const delay = getDelay();
      log(`[Delayed ${delay.toString().padStart(6, ' ')}] Getting`, key);
      return new Promise(resolve => {
        const raw = localStorage.getItem(key);
        log(`[Delayed ${delay.toString().padStart(6, ' ')}] Getting resolved to`, raw);
        return setTimeout(() => {
          log(`[Delayed ${delay.toString().padStart(6, ' ')}] Getting resolves now`);
          resolve(raw);
        }, delay); // ⛔ !!! 50/50 chance this goes above the 5000ms timeout!
      });
    },
    setItem(key, value) {
      log(`[Delayed ${delay.toString().padStart(6, ' ')}] Setting              `, key, value);
      return new Promise(resolve => {
        log(`[Delayed ${delay.toString().padStart(6, ' ')}] Setting resolved     `, key, value);
        return setTimeout(() => {
          log(`[Delayed ${delay.toString().padStart(6, ' ')}] Setting resolves now `, key, value);
          localStorage.setItem(key, value);
          resolve();
        }, 50); // Small delay
      });
    },
    removeItem(key) {
      log('Removing', key);
      return new Promise(resolve => {
        log('Removing resolved', key);
        return setTimeout(() => {
          log('Removing resolves now', key);
          localStorage.removeItem(key);
          resolve();
        }, getDelay()); // Random delay
      })
    }
  },
};
```

This storage implementation retrieves the state with a random delay of 0-10 seconds. If it exceeds the default redux-persist timeout of 5 seconds, state will get reset. So it is a roughly 50/50 chance of getting wiped.

You can [check my 'Snack' example live](https://snack.expo.dev/@jeroenheijmans/repro-redux-persist-809-timeout-wiping-store-data) to see this in action. Increment the counter a few times to persist that state. Then turn preview off and on again to "reload" the app. The state gets read from storage, and you have 50/50 chance of it being either loaded, or reset to initial state.

## Variant 2b: storage errors (confirmable in previous snack.expo.dev)

If you change the `getItem(...)` method for the storage implementation to this:

```javascript
getItem(key) {
  const delay = Math.trunc(Math.random() * 1000);
  return new Promise((resolve, reject) => {
    const raw = localStorage.getItem(key);

    if (delay % 2 === 0) {
      console.log('🛑🛑🛑 Simulating error!');
      return setTimeout(() => reject('error simulated'), delay);
    }

    return setTimeout(() => { resolve(raw); }, delay);
  });
},
```

It will randomly fail about 50% of the time (in this example `getItem` always resolves within the default timeout of 5000. And that also has the effect of resetting to initial state.

Depending on your storage implementation (we use [`react-native-encrypted-storage`](https://github.com/emeraldsanto/react-native-encrypted-storage) in our production app) there might be scenarios where this happens. Who knows, Android or iOS might have all sorts of reasons to throw a (probably temporary) error while accessing storage. For example the SD card might not be ready for reading, would (I imagine) not be an uncommon scenario.

## Variant 3: Storage being 'full' (unconfirmed for me for the moment)

Just to make my comment a bit more "complete" I've added this variant. The Original Post of this issue already mentions and links [a related issue](https://github.com/rt2zz/redux-persist/issues/199) that suggests the same behavior might be caused by a filled up storage causing a reset. If you're reading this, you might want to consider if _this_ is your issue. For my production scenario it's an unlikely cause, as our state is fairly small in size.

PS. This might be different from variant "2B" above because it would happen during `setItem`, but in essence it would also be a bit of the same: errors may occur during storage operations.

**Comment by PatrickWalter387** [comment]
Guys, I just released my own adapter/library for Redux Persist. It’s a file‑based storage solution with extra operations to ensure atomicity and automatic retries in case of unexpected issues — I built this because I was running into data corruption problems with existing persistence libraries, and this approach seems to have solved the problem.

If this can be helpful for your projects, feel free to give it a try — and if you’d like to contribute to the repo, I’d be super grateful 🙏
[react-native-blob-persist](https://github.com/PatrickWalter387/react-native-blob-persist)
